version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linsysequasolver
    volumes:
      - .:/var/www
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: linsysequasolver-nginx
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge